### PR TITLE
Remove use of multiprocessing from the OAuth client

### PR DESCRIPTION
**Pull request by rdeaton-freenome**
## Why are the changes needed?

Multiprocessing in Python is a bit fraught with issues, as it requires that every dependency in the transitive dependency tree of your project supports multiprocessing. We've noticed issues with the way that this code interacts with concurrent task registration that results in trying to open multiple instances of the server, which fails due to listening on the same port.

## What changes were proposed in this pull request?

The multiprocessing usage here didn't actually bring any real benefit, as the intended use was to simply block the requestor's control flow anyways with the use of a queue. This retains the same behavior without the use of any multiprocessing.

## How was this patch tested?

- [ ] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] All commits are signed-off.

### CODE REVIEW

**Review by thomasjpfan — APPROVED** [review]
I tested this PR on an OAuth client and it works. LGTM

**Comment by thomasjpfan** [comment]
@rdeaton-freenome There is a linting issue: https://github.com/flyteorg/flytekit/actions/runs/10185219976/job/28174935429?pr=2626

**Comment by rdeaton-freenome** [comment]
Sorry about that linting issue, fixed in the last commit. Thanks for the quick review!

**Review by pingsutw — APPROVED** [review]

**Comment by rdeaton-freenome** [comment]
I'll just quickly note I expect we'll have a second PR in adjacent areas shortly. We're finding that there's still concurrency issues with registration with auth enabled, but we're certain multiprocessing was both exacerbating the issues and are aware of a long history of multiprocessing issues with grpcio.

**Review by eapolinario — APPROVED** [review]
This is awesome, thank you! This PR solves an outstanding issue we've had on Windows for a long time (https://github.com/flyteorg/flyte/issues/5079 and https://github.com/flyteorg/flyte/issues/4982). I just tested on a windows machine and it worked beautifully.

**Pull request merged**
