### PR TITLE
Fix None deserialization bug in dataclass outputs

### PR DESCRIPTION
**Pull request by JackUrb**
## Tracking issue

Closes flyteorg/flyte/issues/5573

## Why are the changes needed?

As discussed in the linked issue, there is a small issue around serialization/deserialization around inputs/outputs that are optional set as outputs of a dataclass and optional as input to a task.

## What changes were proposed in this pull request?

See details in flyteorg/flyte/issues/5573

## How was this patch tested?

A test case was added that passes locally now, but failed beforehand. The remaining tests still pass.

## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

### CODE REVIEW

**Review by pingsutw — DISMISSED** [review]
LGTM, thanks!

**Review by Future-Outlier — APPROVED** [review]
LGTM, this is really a good catch.

**Comment by pingsutw** [comment]
@JackUrb, could you merge the master into your branch and push it again? thanks

**Comment by JackUrb** [comment]
Rebased again, as it has been a while

**Comment by pingsutw** [comment]
@JackUrb Some tests are failing. mind taking a look

**Comment by JackUrb** [comment]
@pingsutw Fixed - found the source of the issue here

**Review by pingsutw — APPROVED** [review]
lgtm, thank you!

**Pull request merged**
