### PR TITLE
DBT Plugin Api reference

### PR DESCRIPTION
**Pull request by arpitbhardwaj**
Update the plugin docs to include the dbt plugin module.

## Type
 - [ ] Bug Fix
 - [ ] Feature
 - [X] Plugin

## Are all requirements met?

 - [ ] Code completed
 - [ ] Smoke tested
 - [ ] Unit tests added
 - [X] Code documentation added
 - [ ] Any pending items have an associated Issue

## Complete description
 Verified with the local testing for docs using "make html"

## Tracking Issue
Fixes https://github.com/flyteorg/flyte/issues/2966

## Follow-up issue
NA

### CODE REVIEW

**Comment by samhita-alla** [comment]
@arpitbhardwaj, thanks for creating the PR! Can you sign off your commits, please?

**Comment by samhita-alla** [comment]
Can you also include dataclasses present in https://github.com/flyteorg/flytekit/blob/master/plugins/flytekit-dbt/flytekitplugins/dbt/schema.py?

**Comment by arpitbhardwaj** [comment]
@samhita-alla Added classes from schema.py as well and also signed-off the commit.

**Review by pingsutw — APPROVED** [review]
LGTM, thank you @arpitbhardwaj. cc @eapolinario mind taking a look?

**Comment by pingsutw** [comment]
@arpitbhardwaj need to fix the lint error by running `make fmt`

**Comment by eapolinario** [comment]
Change looks good, we need to fix the linting errors though.

**Comment by arpitbhardwaj** [comment]
@pingsutw @eapolinario Fixed the linting errors.

**Review by eapolinario — APPROVED** [review]

**Pull request merged**
