### PR TITLE
Improve task type hint

### PR DESCRIPTION
**Pull request by pingsutw**
# TL;DR
Before:
image

After:
image

## Type
 - [x] Bug Fix
 - [ ] Feature
 - [ ] Plugin

## Are all requirements met?

 - [x] Code completed
 - [ ] Smoke tested
 - [ ] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Complete description
^^^

## Tracking Issue
_NA_

## Follow-up issue
_NA_

### CODE REVIEW

**Comment by kumare3** [comment]
Interesting

**Comment by eapolinario** [comment]
Isn't this essentially voiding any guarantee that tools like mypy or pyright could give users?

**Review by wild-endeavor — APPROVED** [review]

**Review by wild-endeavor — APPROVED** [review]

**Comment by eapolinario** [comment]
mypy still complains about tasks invoked in workflows:
```
❯ cat workflows/example.py
import typing
from flytekit.core.task import task
from flytekit.core.workflow import workflow

@task
def say_hello(name: str) -> str:
    return f"hello {name}!"

@task
def greeting_length(greeting: str) -> int:
    return len(greeting)

@workflow
def wf(name: str) -> typing.Tuple[str, int]:
    greeting = say_hello(name=name)
    greeting_len = greeting_length(greeting=greeting)
    return greeting, greeting_len

❯ mypy workflows/example.py
workflows/example.py:17: error: Incompatible return value type (got "tuple[Promise | VoidPromise | tuple[Any, ...] | None, Promise | VoidPromise | tuple[Any, ...] | None]", expected "tuple[str, int]")  [return-value]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by eapolinario** [comment]
What is the right way to override [`__call__` in `Task`](https://github.com/flyteorg/flytekit/blob/master/flytekit/core/base_task.py#L303-L304) so that it carries the type of the underlying task?

**Comment by pingsutw** [comment]
image

**Comment by eapolinario** [comment]
Nevermind. I tested this by producing a wheel and installing it in a separate venv, but probably messed up on the way. Sorry for the false alarm!

**Review by eapolinario — COMMENTED** [review]
This is awesome!

Should we also add a `py.typed`?

**Comment by wild-endeavor** [comment]
Related to https://github.com/flyteorg/flytekit/pull/1631

**Comment by pingsutw** [comment]
> Should we also add a py.typed?

I'm not sure if we have fixed all the mypy issues. Will do more testing for mypy and add it.

**Comment by eapolinario** [comment]
> > Should we also add a py.typed?
> 
> I'm not sure if we have fixed all the mypy issues. Will do more testing for mypy and add it.

there's at least one case where this is going to break badly: `NamedTuple`. But that shouldn't stop us from shipping this (i.e. we can document this limitation for the time being).

**Pull request merged**
