### PR TITLE
fix: pass gpu resource request and limit in ContainerTask

### PR DESCRIPTION
**Pull request by flixr**
Signed-off-by: Felix Ruess <felix.ruess@roboception.de>

# TL;DR
GPU resource request and limit were not passed on to container for `ContainerTask`. 

## Type
 - [x] Bug Fix
 - [ ] Feature
 - [ ] Plugin

## Are all requirements met?

 - [x] Code completed
 - [x] Smoke tested
 - [x] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Complete description
Actually pass gpu request/limit like for the other Python container tasks...

## Tracking Issue
_NA_

## Follow-up issue
_NA_

### CODE REVIEW

**Review by pingsutw — COMMENTED** [review]
Thanks @flixr, could you fix the linting errors by running `make fmt`

**Comment by flixr** [comment]
`make fmt` just tells me `/bin/sh: 1: pre-commit: not found`
I'm not even sure what there would be to fomat.... trailing comma maybe?

**Comment by pingsutw** [comment]
yes, I think so. you have to install some packages before running make fmt. `pip install -r dev-requirements.txt`

**Comment by mdjong1** [comment]
I would say a risk here is that generally specifying GPU resources is optional and in this implementation it becomes a requirement afaict

**Comment by flixr** [comment]
@mdjong1 it is also optional here, just like all the other resource requests/limits

**Comment by flixr** [comment]
@pingsutw formatted and linter is green, remaining build failures seem to be due to flaky downloads of external things in the tests.

**Review by wild-endeavor — COMMENTED** [review]
hi @flixr thank you! but could you just add a small unit test for this please?

**Comment by flixr** [comment]
@wild-endeavor there don't seem to be any tests for ContainerTask where this fits, not really sure how and where to add tests for this as I'm not familiar with the flytekit codebase.
If you require unit tests for this fix, can you please point me to where these should be added?

I tested it with an actual workflow containing a ContainerTask and it works...

**Comment by pingsutw** [comment]
@flixr yup, we need to add the GPU resources to this line and add an assert to this test. 
```
assert t2.get_container(ssettings).resources.requests[0].name == "gpu"
assert t2.get_container(ssettings).resources.requests[0].value == "1"
```

**Comment by flixr** [comment]
@pingsutw, thanks, added...

**Review by pingsutw — APPROVED** [review]
@flixr Thank you

**Pull request merged**
