### PR TITLE
[wip] Enable `task.remote()` for jupyter notebook

### PR DESCRIPTION
**Pull request by Mecoli1219**
### Screenshots

https://github.com/user-attachments/assets/90183f8a-05c8-4871-92ea-b05b20f8ea5e

## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] All commits are signed-off.

### CODE REVIEW

**Comment by Mecoli1219** [comment]
@kumare3

**Comment by kumare3** [comment]
Haha can you believe I have the same working again

**Comment by Mecoli1219** [comment]
@kumare3 I actually saw your previous [PR #1607](https://github.com/flyteorg/flytekit/pull/1607) from last year. My goal with this update is to make the usage more intuitive and align it more closely with Ray-like usage. But still a work in progress lol

**Comment by kumare3** [comment]
Let me sync with you and Kevin. I don't like this direction very of the right code in a different way for Jupiter versus python.

**Comment by Mecoli1219** [comment]
Oh yes, Kevin doesn't like it either. I am planning to migrate it to flytekit/core PythonTask so that we don't need to add some extra code to execute it remotely on jupyter notebook.

**Comment by thomasjpfan** [comment]
Done in https://github.com/flyteorg/flytekit/pull/2733

**Pull request closed without merging**
