### PR TITLE
Require docker<7.0.0 in setup.py

### PR DESCRIPTION
**Pull request by rahul-theorem**
# TL;DR
Bumps the max version of `docker` in flytekit to `7.0.0`.

## Type
 - [ ] Bug Fix
 - [x] Feature
 - [ ] Plugin

## Are all requirements met?

 - [ ] Code completed
 - [ ] Smoke tested
 - [ ] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Complete description
Upgrades the max version of `docker` in `flytekit` to `7.0.0`.

## Tracking Issue
N/A

## Follow-up issue
N/A

### CODE REVIEW

**Comment by wild-endeavor** [comment]
Thanks!  Would you mind also `make requirements` with python3.7?  (until we have more time to split things up, we're running requirements with the minimum supported python version).  Did you bump this cuz it was causing a conflict somewhere else?

**Comment by eapolinario** [comment]
@wild-endeavor , original context: https://flyte-org.slack.com/archives/CREL4QVAQ/p1660922404113919. We should make this less

**Comment by wild-endeavor** [comment]
yea that sounds good.  we're not using it for much really doesn't need to be that strict.

**Comment by wild-endeavor** [comment]
@rahul-theorem would you mind updating the pr?

**Comment by rahul-theorem** [comment]
Hey @wild-endeavor updating this right now, just needed to switch my python env to 3.7

**Comment by wild-endeavor** [comment]
yeah could you try that?  that is weird.  and you're running with python 3.7 right?  i think we still rely on that.  if a clean venv is still causing downgrades let us know.  thanks!

**Review by wild-endeavor — APPROVED** [review]

**Comment by wild-endeavor** [comment]
actually holding off... will try to run this later on a new venv

**Comment by wild-endeavor** [comment]
oh it looks like all the downgrades are happening in the doc requirements file.  i think that's okay.  it looks like the previous one was generated with 3.9 and now we're using 3.7.  i think that's fine. we can bump again separately if needed.  3.9 is probably okay for docs though. cc @eapolinario 

merging.

**Pull request merged**
