### PR TITLE
refactor(core): Update with_overrides signatures and type hints

### PR DESCRIPTION
**Pull request by pingsutw**
## Tracking issue
NA

## Why are the changes needed?
Cannot know the args that with_override take

## What changes were proposed in this pull request?
Update with_overrides signatures and type hints

## How was this patch tested?
local

### Setup process
NA

## Check all the applicable boxes 

- [x] I updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Related PRs
NA

## Docs link
NA

### CODE REVIEW

**Comment by pingsutw** [comment]
cc @fg91 since you're also using `with_overrides`

**Review by wild-endeavor — APPROVED** [review]

**Comment by fg91** [comment]
@fellhorn fyi

**Comment by fellhorn** [comment]
> @fellhorn fyi

Thanks, we need to ignore the `Promise` types though and thus anyway can't have type hints for the `with_overrides` :/
See https://github.com/flyteorg/flyte/issues/3682

It's either having type hints for the Promise types for us or having type checks for task & workflow inputs & outputs.

**Comment by pingsutw** [comment]
> Thanks, we need to ignore the Promise types though and thus anyway can't have type hints for the with_overrides :/

@fellhorn could we merge this first and then figure out the type issue later? this will allow us to see the type hint in the IDE for` with_override`. Also, it cleans up the code. (remove `if "container_image" in kwargs` ...)

**Review by wild-endeavor — APPROVED** [review]

**Comment by fellhorn** [comment]
> > Thanks, we need to ignore the Promise types though and thus anyway can't have type hints for the with_overrides :/
> 
> @fellhorn could we merge this first and then figure out the type issue later? this will allow us to see the type hint in the IDE for` with_override`. Also, it cleans up the code. (remove `if "container_image" in kwargs` ...)

Sorry, I overlooked your message.
Yes, please merge this PR. My answer to fg91 was rather about our internal `flytekit` wrapper, that helps us to check the runtime types instead of the graph types. I imagine my comment is not relevant for other `flytekit` users.

**Pull request merged**
