### PR TITLE
Propagate custom_info Dict through agent Resource

### PR DESCRIPTION
**Pull request by ddl-ebrown**
See also https://github.com/flyteorg/flyte/pull/5391

## Why are the changes needed?

- The agent defines a Resource return type with values:

   * outputs
   * message
   * log_links
   * phase

   These are all a part of the underlying protobuf contract defined in
   flyteidl.

   However, the message field custom_info from the protobuf is not here

   google.protobuf.Struct custom_info

   https://github.com/flyteorg/flyte/blob/519080b6e4e53fc0e216b5715ad9b5b5270f35c0/flyteidl/protos/flyteidl/admin/agent.proto#L140

   This field was added in https://github.com/flyteorg/flyte/pull/4874
   but never made it into the corresponding flytekit PR
   https://github.com/flyteorg/flytekit/pull/2146

 - It's useful for agents to return additional metadata about the job,
   and it looks like custom_info is the intended location

 - Make a minor refactor to how the agent responds to requests that
   return Resource by implementing to_flyte_idl / from_flyte_idl
   directly

## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] All commits are signed-off.

### CODE REVIEW

**Comment by ddl-rliu** [comment]
Tracking issue: https://github.com/flyteorg/flyte/issues/5603

**Comment by pingsutw** [comment]
@ddl-rliu Could you rebase the PR to fix the CI error?

**Comment by pingsutw** [comment]
something wrong in the github
Screenshot 2024-09-05 at 11 14 06 AM

**Comment by ddl-rliu** [comment]
Fixed!

**Review by pingsutw — APPROVED** [review]

**Comment by pingsutw** [comment]
@ddl-rliu overall lgtm, some tests are failing though.

**Comment by ddl-rliu** [comment]
test errors should be fixed now 👍

**Review by eapolinario — APPROVED** [review]

**Pull request merged**
