### PR TITLE
#minor Revert "Adopt flyteidl's ordered variable map change" #608

### PR DESCRIPTION
**Pull request by mayitbeegh**
# TL;DR
Reverts [Change variable map to repeated map entries for ordering #206](https://github.com/flyteorg/flytekit/pull/608) as a result of the flyteidl reversion [Revert variable ordering change PR #220](https://github.com/flyteorg/flyteidl/pull/220) in release 0.21.0.

## Type
 - [x] Bug Fix
 - [ ] Feature
 - [ ] Plugin

## Are all requirements met?

 - [x] Code completed
 - [ ] Smoke tested
 - [x] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Tracking Issue
https://github.com/lyft/flyte/issues/<number>

## Follow-up issue
_NA_

### CODE REVIEW

**Comment by wild-endeavor** [comment]
keep in mind that the release process for this repo is still manual (and i think we should keep it that way for now).  so the #minor in the title of the PR won't do anything, but that's okay, still a good reminder to us.

**Review by katrogan — DISMISSED** [review]

**Comment by katrogan** [comment]
Mind filling out the PR description before merging?

**Review by katrogan — APPROVED** [review]

**Review by wild-endeavor — APPROVED** [review]
let's release this as v0.23.0b0

**Comment by wild-endeavor** [comment]
why do not merge?

**Comment by mayitbeegh** [comment]
> why do not merge?

Should I leave the workflow changes in?

**Comment by wild-endeavor** [comment]
I think this is okay to merge - we'll be merging in https://github.com/flyteorg/flytekit/pull/644 soon which will turn them back on in a different way.

**Pull request merged**
