### PR TITLE
[v1.8 Patch] Restrict grpcio<1.53.1

### PR DESCRIPTION
**Pull request by eapolinario**
# TL;DR
_Please replace this text with a description of what this PR accomplishes._

## Type
 - [ ] Bug Fix
 - [ ] Feature
 - [ ] Plugin

## Are all requirements met?

 - [ ] Code completed
 - [ ] Smoke tested
 - [ ] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Complete description
 _How did you fix the bug, make the feature etc. Link to any design docs etc_

## Tracking Issue
https://github.com/flyteorg/flyte/issues/<number>

## Follow-up issue
_NA_
OR
_https://github.com/flyteorg/flyte/issues/<number>_

### CODE REVIEW

**Review by wild-endeavor — DISMISSED** [review]

**Review by pingsutw — APPROVED** [review]

**Review by wild-endeavor — APPROVED** [review]

**Comment by honnix** [comment]
What is the reason for this restriction? Why is it not applied to main branch? Thanks.

**Comment by eapolinario** [comment]
We're actually also going to apply this to the main branch: https://github.com/flyteorg/flytekit/pull/1767. 

The reason is described in https://github.com/grpc/grpc/issues/33935. Basically a regression in the `grpcio` library.

**Comment by honnix** [comment]
Thank you. That's very good to know!

**Comment by honnix** [comment]
@eapolinario Sorry for coming back to this. Given https://security.snyk.io/vuln/SNYK-PYTHON-GRPCIO-5834443, is it more important to pin to avoid this bug or unpin to resolve the vulnerability? As I understood this particular bug only impact a certain setup. Is that correct?

**Pull request merged**
