### PR TITLE
Remove pyarrow as a direct dependency

### PR DESCRIPTION
**Pull request by thomasjpfan**
## Tracking issue
Continues https://github.com/flyteorg/flyte/issues/4418

## Why are the changes needed?

From https://github.com/flyteorg/flyte/issues/4418#issuecomment-1936333515, `pyarrow` is the largest dependency. This PR removes the dependency and lazy loads it.

## What changes were proposed in this pull request?

With this PR, `pyarrow` is now lazy loaded. The lazy loading mechanism is the same as the one used for `pandas`.

## How was this patch tested?

In two of the test environments, `pyarrow` is removed to make sure `flytekit` works without `pyarrow` installed.

### CODE REVIEW

**Comment by thomasjpfan** [comment]
I am putting this as a draft. Removing `pyarrow` removes the indirect dependency on `numpy`. (`pyarrow` was the only library that depends on `numpy`).

I need to make sure `flytekit` works without `numpy` installed as well.

**Comment by thomasjpfan** [comment]
@pingsutw This PR removes one of the biggest dependencies. On Linux amd64, `pyarrow` uncompressed is 140MB.

The downside is that `pandas_df.to_parquet` will not work out of the box with `StructuredDataset`.

**Comment by pingsutw** [comment]
> The downside is that pandas_df.to_parquet will not work out of the box, (which is used by StructuredDataset)

I just tested it and the error message is clear, so I think it's fine.

```python
import pandas as pd

from flytekit import task, workflow, StructuredDataset, ImageSpec

df = pd.DataFrame({"Name": ["Tom", "Joseph"], "Age": [1, 22]})

new_flytekit = "git+https://github.com/thomasjpfan/flytekit.git@603d3996bc4ed6907ba6c0296ae395e80f8e1dfc"
image_spec = ImageSpec(
    base_image="python:3.10-slim-bookworm",
    registry="pingsutw",
    packages=[new_flytekit, "pandas"],
    apt_packages=["git"]
)


@task(container_image=image_spec)
def t1(sd: StructuredDataset) -> StructuredDataset:
    print(sd.open(pd.DataFrame).all())
    return sd


@task(container_image=image_spec.with_packages("pyarrow"))
def t2(sd: StructuredDataset) -> StructuredDataset:
    print(sd.open(pd.DataFrame).all())
    return sd


@workflow
def wf():
    t1(sd=StructuredDataset(df))
    t2(sd=StructuredDataset(df))
```
Screenshot 2024-07-12 at 3 55 36 PM

**Comment by pingsutw** [comment]
@eapolinario @wild-endeavor wdyt

**Review by pingsutw — APPROVED** [review]

**Pull request merged**
