### PR TITLE
Revert #2303

### PR DESCRIPTION
**Pull request by pingsutw**
## Tracking issue
https://github.com/flyteorg/flytekit/pull/2303#issuecomment-2322364266

## Why are the changes needed?
1.  This change is leading to some weird behavior and I think part of it is working by coincidence. We noticed this because of a test that was failing in Pycharm but passing in CI. But you can reproduce a similar error just with pytest.

2. Cannot submit a task from the notebook after this commit

## What changes were proposed in this pull request?
Revert some of the changes in https://github.com/flyteorg/flytekit/pull/2303

## How was this patch tested?
unit test

## Check all the applicable boxes 

- [x] I updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Related PRs
NA

## Docs link
NA

### CODE REVIEW

**Comment by pingsutw** [comment]
cc @wild-endeavor

**Comment by pingsutw** [comment]
cc @eapolinario

**Comment by pingsutw** [comment]
@ddl-ebrown

**Comment by pingsutw** [comment]
Sorry, I ping you at the wrong PR. I was trying to ping you at https://github.com/flyteorg/flyte/pull/5740

**Review by wild-endeavor — APPROVED** [review]

**Pull request merged**
