### PR TITLE
refactor(core): Improve dataclass attribute serialization

### PR DESCRIPTION
**Pull request by pingsutw**
## Tracking issue
NA

## Why are the changes needed?
The Flytefile is not uploaded to S3 when having that ​​`from ­­­future­­­ import annotations`​​ import inside the file. 

That's because `dataclasses.fields(python_type)[0].type` will return a string ('flytefile') instead of the actual type when postponed annotations is enabled.

## What changes were proposed in this pull request?
Use `typing.get_type_hints` to explicitly get the type from dataclass.

## How was this patch tested?
remote cluster

### Setup process

```python
from __future__ import annotations
from flytekit import task, workflow, ImageSpec
from flytekit.types.file import FlyteFile
from dataclasses import dataclass


new_flytekit = "git+https://github.com/flyteorg/flytekit.git@c5e6cefbc99f8db1190a87c10d921445f3e7b7d1"

custom_image = ImageSpec(
    registry="ghcr.io/flyteorg",
    packages=[new_flytekit],
    apt_packages=["git"],
)

@dataclass
class DebugOutput:
    file: FlyteFile


def get_file_test() -> FlyteFile:
    local_path = "file.txt"
    f = open(local_path, "a")
    f.write("1")
    f.close()
    return FlyteFile(local_path)


@task(container_image=custom_image)
def debug() -> DebugOutput:
    file = get_file_test()
    return DebugOutput(file=file)


@workflow
def wf() -> DebugOutput:
    return debug()


if __name__ == '__main__':
    wf()
```

```python
from __future__ import annotations
from flytekit import task, workflow, ImageSpec
from flytekit.types.file import FlyteFile
from dataclasses import dataclass


new_flytekit = "git+https://github.com/flyteorg/flytekit.git@c5e6cefbc99f8db1190a87c10d921445f3e7b7d1"

custom_image = ImageSpec(
    registry="ghcr.io/flyteorg",
    packages=[new_flytekit],
    apt_packages=["git"],
)

@dataclass
class DebugOutput:
    file: "FlyteFile"


def get_file_test() -> FlyteFile:
    local_path = "file.txt"
    f = open(local_path, "a")
    f.write("1")
    f.close()
    return FlyteFile(local_path)


@task(container_image=custom_image)
def debug() -> DebugOutput:
    file = get_file_test()
    return DebugOutput(file=file)


@workflow
def wf() -> DebugOutput:
    return debug()


if __name__ == '__main__':
    wf()
```

### Screenshots
Screenshot 2024-06-25 at 3 06 12 AM

## Check all the applicable boxes 

- [x] I updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Related PRs
NA

## Docs link
NA

### CODE REVIEW

**Review by wild-endeavor — DISMISSED** [review]
could you add a small unit test though?  this should be easily unit testable right?

**Comment by wild-endeavor** [comment]
this test passes on master...

**Comment by pingsutw** [comment]
fixing it

**Review by wild-endeavor — APPROVED** [review]

**Review by eapolinario — APPROVED** [review]
That's pretty cool. Thank you!

**Comment by pingsutw** [comment]
FYI @fiedlerNr9

**Pull request merged**
