### PR TITLE
add pod_template and pod_template_name arguments for ContainerTask

### PR DESCRIPTION
**Pull request by flixr**
# TL;DR
Support pod_template and pod_template_name arguments for ContainerTask

Depends on https://github.com/flyteorg/flyteidl/pull/368

## Type
 - [ ] Bug Fix
 - [x] Feature
 - [ ] Plugin

## Are all requirements met?

 - [x] Code completed
 - [x] Smoke tested
 - [x] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Complete description
Nearly a copy of what was added to  `PythonAutoContainerTask` with #1425 

## Tracking Issue
https://github.com/flyteorg/flyte/issues/3123
## Follow-up issue
_NA_

### CODE REVIEW

**Comment by flixr** [comment]
I have the feeling that the task structure in flytekit should be refactored instead of adding this in many places...
Should this be added to the base `PythonTask` instead?

**Comment by wild-endeavor** [comment]
I'm comfortable leaving this as separate pieces of code for the time being.  Maybe we can just refactor out the `_serialize_pod_spec` function into something common though?  they look to be pretty similar.

**Comment by flixr** [comment]
Did you have a chance to test it all together?
Then I can refactor it a bit...

**Comment by flixr** [comment]
I left the pod plugin as is... could either be refactored to use PodTemplate as well or completely removed (eventually).
But that can be done in a separate PR...

**Comment by wild-endeavor** [comment]
would you mind adding a few unit tests please?

**Comment by wild-endeavor** [comment]
And oh, we need the IDL PR (https://github.com/flyteorg/flyteidl/pull/368) to go in, so we can get the release version and bump the requirement in setup.py.

**Comment by flixr** [comment]
Thanks @wild-endeavor, tested the updated sandbox with backend changes: works with this PR and flyteidl updates.

Also added a unit test.

**Comment by flixr** [comment]
> @flixr https://github.com/flyteorg/flyteidl/releases/tag/v1.3.12 was merged and cut this morning. mind bumping the version in setup.py please? the tests that are failing like tests/flytekit/unit/models/test_tasks.py::test_k8s_pod will also pass.

done

**Comment by wild-endeavor** [comment]
@flixr can you take a look at the failing test please?  i think it's just a simple pip dependency change.  doc requirements probably just needs to be recompiled.

**Comment by hamersaw** [comment]
@flixr do you have a timeline for the test fix? Would be great if we could get this wrapped up!

**Comment by flixr** [comment]
Sorry, was on vacation for one week. Updated the doc requirements as well..

**Review by wild-endeavor — APPROVED** [review]

**Pull request merged**
