### PR TITLE
Update task.py

### PR DESCRIPTION
**Pull request by RaghavMangla**
## Why are the changes needed?

Issue description: 
[the papermill example](https://docs.flyte.org/projects/cookbook/en/latest/auto_examples/papermill_plugin/simple.html) in the flyte docs lacks info on rendering the notebook in a deck. 

slack thread for reference: https://discuss.flyte.org/t/15484282/hi-all-flyte-rookie-here-maybe-you-can-help-me-out-i-m-tryin#33b0b813-6822-4451-8977-eaec3387a4ff

## What changes were proposed in this pull request?

to achieve this, added render_deck=True and enable_deck=True to the notebooktask.

### CODE REVIEW

**Review by wild-endeavor — APPROVED** [review]

**Comment by RaghavMangla** [comment]
@kumare3 @eapolinario @pingsutw @cosmicBboy @samhita-alla @thomasjpfan @Future-Outlier can u pls review this pr

**Comment by Future-Outlier** [comment]
> @kumare3 @eapolinario @pingsutw @cosmicBboy @samhita-alla @thomasjpfan @Future-Outlier can u pls review this pr

Can you run a workflow example like this and prove to us that it works as expected?
https://github.com/flyteorg/flytekit/pull/1870

**Comment by RaghavMangla** [comment]
I was getting a few version conflicts when I tried to use make html command
in docs Directory, can u pls assist me with this? Like how to run a working
example

**Comment by RaghavMangla** [comment]
@Future-Outlier this is a documentation change, is a workflow required still?

**Comment by RaghavMangla** [comment]
image
this is what i got on rendering html page for this, can u pls mention which is the new documentation for flyte docs

**Comment by RaghavMangla** [comment]
saw that my PR falied on one of the tests, any ideas on how to fix that?

**Review by Future-Outlier — APPROVED** [review]

**Comment by RaghavMangla** [comment]
will this PR be considered for hacktoberfest? @wild-endeavor @Future-Outlier @samhita-alla

**Pull request merged**
