### PR TITLE
FlyteRemote API examples

### PR DESCRIPTION
**Pull request by samhita-alla**
Signed-off-by: Samhita Alla <aallasamhita@gmail.com>

# TL;DR
Added examples to showcase FlyteRemote API.

## Type
 - [ ] Bug Fix
 - [ ] Feature
 - [ ] Plugin

## Are all requirements met?

 - [ ] Code completed
 - [ ] Smoke tested
 - [ ] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Complete description
 _How did you fix the bug, make the feature etc. Link to any design docs etc_

## Tracking Issue
Fixes https://github.com/flyteorg/flyte/issues/1844

## Follow-up issue
_NA_
OR
_https://github.com/flyteorg/flyte/issues/<number>_

### CODE REVIEW

**Comment by samhita-alla** [comment]
@eapolinario, I haven't understood _List workflow ids, workflows, and launchplans are not currently exposed in flyteremote._ in the third point of the issue description. Could you please elaborate?

**Comment by eapolinario** [comment]
> @eapolinario, I haven't understood _List workflow ids, workflows, and launchplans are not currently exposed in flyteremote._ in the third point of the issue description. Could you please elaborate?

@samhita-alla , you're right, we only have list [recent executions and tasks](https://github.com/flyteorg/flytekit/blob/master/flytekit/remote/remote.py#L302-L317) in remote right now. That said, adding that to flyteremote would not be hard, but let's not do that now.

**Comment by kumare3** [comment]
this is pretty good, just `register_script` is remaining. but we can add it as the next step. I am thinking should these all be in flytesnacks too?

**Comment by samhita-alla** [comment]
> this is pretty good, just register_script is remaining. but we can add it as the next step. I am thinking should these all be in flytesnacks too?

Since this essentially is an explanation of or a dive into the FlyteRemote API, I thought API Reference would be a good place to have these examples. Flytesnacks is more of a real-time examples repository. Let me know what you think.

**Comment by kumare3** [comment]
@samhita-alla can you please fix the lint?

**Comment by samhita-alla** [comment]
@kumare3, fixed the lint issue.

**Review by kumare3 — APPROVED** [review]

**Pull request merged**
