### PR TITLE
Try to fix grpcio upper bound

### PR DESCRIPTION
**Pull request by honnix**
# TL;DR

Try to fix grpcio upper bound

## Type
 - [x] Bug Fix
 - [ ] Feature
 - [ ] Plugin

## Are all requirements met?

 - [x] Code completed
 - [ ] Smoke tested
 - [ ] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Complete description
~Details are kept in https://github.com/flyteorg/flyte/issues/3079~ Not a correct issue.

## Tracking Issue
~https://github.com/flyteorg/flyte/issues/3079~ Not a correct issue.

## Follow-up issue
_NA_

### CODE REVIEW

**Comment by honnix** [comment]
For some reason, I cannot successfully run `make requirements`

```
    best_candidate = self.finder.find_requirement(req, upgrade)
  File "/Users/honnix/.pyenv/versions/flytekit-3.7/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 942, in find_requirement
    "No matching distribution found for {}".format(req)
pip._internal.exceptions.DistributionNotFound: No matching distribution found for scikit-learn==1.1.1 (from -r doc-requirements.in (line 19))
make: *** [doc-requirements.txt] Error 1
```

It would be great if someone can help me regenerate those `.txt` files.

**Comment by honnix** [comment]
> For some reason, I cannot successfully run `make requirements`
> 
> ```
>     best_candidate = self.finder.find_requirement(req, upgrade)
>   File "/Users/honnix/.pyenv/versions/flytekit-3.7/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 942, in find_requirement
>     "No matching distribution found for {}".format(req)
> pip._internal.exceptions.DistributionNotFound: No matching distribution found for scikit-learn==1.1.1 (from -r doc-requirements.in (line 19))
> make: *** [doc-requirements.txt] Error 1
> ```
> 
> It would be great if someone can help me regenerate those `.txt` files.

OK, this doc-requirements.in requires python 3.9 while other requires python 3.7. 🤦

**Comment by honnix** [comment]
Not sure this is needed anymore. But we can at least remove the `<2.0` part? Seems confusing.

**Review by pingsutw — APPROVED** [review]

**Comment by eapolinario** [comment]
This is not needed.

**Pull request closed without merging**
