### PR TITLE
Add log streaming to papermill plugin

### PR DESCRIPTION
**Pull request by CalvinLeather**
# TL;DR
Enabling the 

Meant to open this in my fork for internal review, but will leave up as draft and wrap up tomorrow with a better test + smoke test.

Smoke test:
image

## Type
 - [ ] Bug Fix
 - [x] Feature
 - [ ] Plugin

## Are all requirements met?

 - [ ] Code completed
 - [ ] Smoke tested
 - [ ] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Complete description
 _How did you fix the bug, make the feature etc. Link to any design docs etc_

## Tracking Issue
https://github.com/flyteorg/flyte/issues/<number>

## Follow-up issue
_NA_
OR
_https://github.com/flyteorg/flyte/issues/<number>_

### CODE REVIEW

**Comment by pingsutw** [comment]
@CalvinLeather is it ready to be merged?

**Comment by pingsutw** [comment]
Kindly ping @CalvinLeather

**Comment by kumare3** [comment]
@pingsutw can we just cherry-pick the change and merge it in. I think this is a useful PR

**Comment by pingsutw** [comment]
Will do

**Review by pingsutw — APPROVED** [review]

**Pull request merged**
