### PR TITLE
Skyplane flytekit plugin

### PR DESCRIPTION
**Pull request by 10sharmashivam**
## Tracking issue
Reference Issue- [Skyplane flytekit plugin](https://github.com/flyteorg/flyte/issues/3005)

## Why are the changes needed?

Skyplane plugin adds the capability of transferring data using Skyplane to Flyte. Skyplane allows for significantly faster and cheaper data transfers compared to traditional methods, enhancing the overall efficiency of data workflows.

## What changes were proposed in this pull request?

	•	Implementation of a new Flyte plugin to facilitate data transfers using Skyplane.
	•	Definition of SkyplaneJob for configuring data transfer jobs.
	•	Creation of SkyplaneFunctionTask to integrate with Flyte, including command construction for Skyplane operations.
	•	Registration of the task plugin within Flyte’s plugin system.

## How was this patch tested?

I have not been able to run a full end-to-end test as I currently do not have access to cloud storage locations. However, I validated the general structure of the plugin, and I’d appreciate any recommendations for accessible cloud storage locations for testing purposes.

## Additional Comments

I’m submitting this PR as an initial implementation of the Skyplane plugin integration. At this stage, I’ve structured the plugin, created the SkyplaneJob and SkyplaneFunctionTask classes, and registered the plugin with Flyte. 

And as mentioned in some old comments on parent issue for this [PR](https://github.com/flyteorg/flyte/issues/3005), about launching machines and apache arrow based file system (I believe that’s what arrow FS means there, please let me know if I am correct), how can I go about it?

I’d greatly appreciate any feedback or guidance to ensure that I’m on the right track with this implementation, especially regarding the integration with Skyplane’s data transfer features. I’ll continue to refine the code and address any changes based on the team’s suggestions.

Looking forward to your insights!

## Next Steps-

I plan to enhance error handling and logging in the upcoming iterations of this Skyplane plugin.
And likewise, this plugin will mature.

## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] All commits are signed off.

### CODE REVIEW

**Comment by 10sharmashivam** [comment]
Quick update: I’ve tried implementing the error handling and logging as planned. This should make debugging and future maintenance easier. Let me know if there’s anything specific you’d like me to adjust!

**Comment by davidmirror-ops** [comment]
@10sharmashivam thank you! as per testing, looks like AWS Free Tier includes 5GB of S3 standard storage, would you be able to try it?

**Comment by kumare3** [comment]
I am not sure if we should add this plugin. Skyplane seems to be a defunct project now?

**Comment by 10sharmashivam** [comment]
@kumare3 Thank you for your feedback on the Skyplane plugin. I understand your concerns regarding skyplane's maintenance status. I encountered several issues myself while working with Skyplane, such as its lack of support for Python versions beyond 3.10, which aligns with your observation.

Given this, I understand if there are reservations about including this plugin in the Flyte ecosystem. I’m open to exploring other options and contributing to other issues within the project in mean time.

As for alternatives to Skyplane, I’ve been researching potential open-source solutions. One promising candidate is Rclone, a command-line program that effectively manages files on cloud storage and supports a wide range of providers. Rclone stands out with its multi-threaded transfer capabilities, enabling faster data movement, as well as its broad compatibility with numerous cloud services and advanced features like synchronization and encryption.

I’m keen on discussing these options further and seeing how I can contribute to enhancing Flyte’s capabilities. Thank you for considering my suggestions.

**Comment by 10sharmashivam** [comment]
Hi @davidmirror-ops @kumare3, I wanted to check in and see if there’s any further feedback on the Skyplane plugin. Should I proceed with an skyplane only, or some alternative like Rclone, given Skyplane’s status? or is there another option the team might be exploring? I’m very interested in contributing further and exploring ways to bring this functionality to Flyte. If there’s anything specific I could add or clarify, I’m happy to help!

Thanks!

**Comment by davidmirror-ops** [comment]
Hey @10sharmashivam 
Sorry, this issue has been around for a while but considering that Skypilot doesn't seem to be very active recently and also how Flyte has already improved filesystem performance natively, I think we should not move forward with building this plugin.
We'll still count this towards the Hacktoberfest contributions.
Thank you and sorry again.

**Comment by 10sharmashivam** [comment]
Hi @davidmirror-ops,

Thank you for the update and for considering my contribution to Hacktoberfest. I understand the decision regarding the Skyplane plugin, and I appreciate your feedback.

I will look into other issues and try contributing to them to enhance Flyte’s capabilities further and support the community.

Thanks again!

**Pull request closed without merging**
