### PR TITLE
[WIP] Debug default upload

### PR DESCRIPTION
**Pull request by Future-Outlier**
## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] All commits are signed-off.

### CODE REVIEW

**Comment by Future-Outlier** [comment]
put some logs

## new context for FilePathTransformer
```python
Remote Execution:  @@@ should_upload:  True
@@@ source_path:  /Users/future-outlier/code/dev/flytekit/build/local_example.txt
@@@ headers:  {}
@@@ remote_path:  None
@@@ should_upload:  False
Running Execution on Remote.
[2024-10-31T15:00:06.788+0800] {__init__.py:14} INFO - Pandas backend loaded 2.2.3
[2024-10-31T15:00:06.790+0800] {__init__.py:25} INFO - Numpy backend loaded 1.26.4
[2024-10-31T15:00:06.791+0800] {__init__.py:35} INFO - Pyspark backend loaded 3.5.2
[2024-10-31T15:00:06.791+0800] {__init__.py:43} INFO - Python backend loaded
Image localhost:30000/flytekit:qoVyL3nOf90RZOClkyJXBA found. Skip building.
@@@ should_upload:  True
@@@ source_path:  /Users/future-outlier/code/dev/flytekit/build/local_example.txt
@@@ headers:  {}
@@@ remote_path:  None
```

## use the default context
```python
@@@ source_path:  /Users/future-outlier/code/dev/flytekit/build/local_example.txt
@@@ headers:  {}
@@@ remote_path:  None
@@@ should_upload:  True
@@@ source_path:  /var/folders/3z/bsm4cddd4q18b_jc_2b2my4h0000gn/T/flyte-9gwfsnx_/raw/ffb0da4c60019751dfa8fa14bf2e7156/local_example.txt
@@@ headers:  {}
@@@ remote_path:  None
Running Execution on Remote.
[2024-10-31T15:06:16.912+0800] {__init__.py:14} INFO - Pandas backend loaded 2.2.3
[2024-10-31T15:06:16.915+0800] {__init__.py:25} INFO - Numpy backend loaded 1.26.4
[2024-10-31T15:06:16.917+0800] {__init__.py:35} INFO - Pyspark backend loaded 3.5.2
[2024-10-31T15:06:16.917+0800] {__init__.py:43} INFO - Python backend loaded
Image localhost:30000/flytekit:qoVyL3nOf90RZOClkyJXBA found. Skip building.
@@@ should_upload:  True
@@@ source_path:  /Users/future-outlier/code/dev/flytekit/build/local_example.txt
@@@ headers:  {}
@@@ remote_path:  None
```

**Comment by Future-Outlier** [comment]
the context's file access's raw_output_fs and raw_output_prefix are wrong, not sure why

image

**Comment by Future-Outlier** [comment]
I’ve decided to prioritize the gate-feature and stop here. 

The main issue is that if we don’t create a new context at the top of the context stack, the original context will set `file_access` properties, like `raw_output_fs` and `raw_output_prefix`, to use local storage. 

However, if we create a new context, then `file_access` will set `raw_output_fs` and `raw_output_prefix` to use remote storage instead. 

The most confused things for me is I don't know why the default context use local storage.

**Comment by eapolinario** [comment]
Also, just want to confirm, this is pre-existing behavior, right? As in, it reproes in released versions of flytekit.

**Comment by Future-Outlier** [comment]
> Also, just want to confirm, this is pre-existing behavior, right? As in, it reproes in released versions of flytekit.

yes you are right, I will solve this today

**Pull request closed without merging**
