### PR TITLE
Fix sql alchemy plugin error `module 'pandas.io' has no attribute 'common' `

### PR DESCRIPTION
**Pull request by Future-Outlier**
## Tracking issue
https://github.com/flyteorg/flyte/issues/749

## Why and What?
1. why we restrict sql_alchemy plugin < = 2.1.4?
image
if you use latest pandas version, you will find that there's a bug or interface is changed when running example.
(not sure which is the answer yet.)
image

2. why we use `from pandas.io.common import is_fsspec_url`?
from @pingsutw 's advice, we found that some of pandas module need to be loaded entirely.

## How was this patch tested?
1. Use a python example
```python
from flytekit import kwtypes, task, workflow
from flytekit.types.schema import FlyteSchema
from flytekitplugins.sqlalchemy import SQLAlchemyConfig, SQLAlchemyTask

DATABASE_URI = "postgresql://reader:NWDMCE5xdipIjRrp@hh-pgsql-public.ebi.ac.uk:5432/pfmegrnargs"

# Here we define the schema of the expected output of the query, which we then re-use in the `get_mean_length` task.
DataSchema = FlyteSchema[kwtypes(sequence_length=int)]

sql_task = SQLAlchemyTask(
    "rna",
    query_template="""
        select len as sequence_length from rna
        where len >= {{ .inputs.min_length }}
        and len <= {{ .inputs.max_length }}
        limit {{ .inputs.limit }}
    """,
    inputs=kwtypes(min_length=int, max_length=int, limit=int),
    output_schema_type=DataSchema,
    task_config=SQLAlchemyConfig(uri=DATABASE_URI),
    container_image="localhost:30000/flytekit:sql",
)

@task
def get_mean_length(data: DataSchema) -> float:
    dataframe = data.open().all()
    return dataframe["sequence_length"].mean().item()

@workflow
def my_wf(min_length: int, max_length: int, limit: int) -> float:
    return get_mean_length(data=sql_task(min_length=min_length, max_length=max_length, limit=limit))


if __name__ == "__main__":
    print(f"Running {__file__} main...")
    print(my_wf(min_length=50, max_length=200, limit=5))
```
2. build an image to test it

### Screenshots
image
image

## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

### CODE REVIEW

**Comment by eapolinario** [comment]
Can you more details to the description? For example, what's the error? also, can you link to a github issue on the sqlalchemy project?

**Comment by Future-Outlier** [comment]
> Can you more details to the description? For example, what's the error? also, can you link to a github issue on the sqlalchemy project?

Yes, will update more information here.

**Comment by Future-Outlier** [comment]
image

**Comment by Future-Outlier** [comment]
It is super weird that I can't reproduce the error in the container's python env.
## error in the container by command `pyflyte run`
```python
from flytekit import kwtypes, task, workflow
from flytekit.types.schema import FlyteSchema
from flytekitplugins.sqlalchemy import SQLAlchemyConfig, SQLAlchemyTask

DATABASE_URI = "postgresql://reader:NWDMCE5xdipIjRrp@hh-pgsql-public.ebi.ac.uk:5432/pfmegrnargs"

# Here we define the schema of the expected output of the query, which we then re-use in the `get_mean_length` task.
DataSchema = FlyteSchema[kwtypes(sequence_length=int)]

sql_task = SQLAlchemyTask(
    "rna",
    query_template="""
        select len as sequence_length from rna
        where len >= {{ .inputs.min_length }}
        and len <= {{ .inputs.max_length }}
        limit {{ .inputs.limit }}
    """,
    inputs=kwtypes(min_length=int, max_length=int, limit=int),
    output_schema_type=DataSchema,
    task_config=SQLAlchemyConfig(uri=DATABASE_URI),
    container_image="localhost:30000/flytekit:sql",
)

@task
def get_mean_length(data: DataSchema) -> float:
    dataframe = data.open().all()
    return dataframe["sequence_length"].mean().item()

@workflow
def my_wf(min_length: int, max_length: int, limit: int) -> float:
    return get_mean_length(data=sql_task(min_length=min_length, max_length=max_length, limit=limit))


if __name__ == "__main__":
    print(f"Running {__file__} main...")
    print(my_wf(min_length=50, max_length=200, limit=5))
```
example reference: https://docs.flyte.org/en/latest/flytesnacks/examples/sql_plugin/sql_alchemy.html#sql-alchemy

image

## No error in the container (python terminal)
image

**Review by pingsutw — APPROVED** [review]

**Pull request merged**
