### PR TITLE
Update log level for structured dataset

### PR DESCRIPTION
**Pull request by pingsutw**
Signed-off-by: Kevin Su <pingsutw@apache.org>

# TL;DR
Change the log level to debug. Otherwise, we will get lots of warnings about structured datasets while running the workflow 
```bash
{"asctime": "2022-12-25 22:57:07,317", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.PandasToParquetEncodingHandler object at 0x7fce624a8220> with format parquet as default for <class 'pandas.core.frame.DataFrame'>, parquet already specified."}
{"asctime": "2022-12-25 22:57:07,317", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.PandasToParquetEncodingHandler object at 0x7fce624a8220> with format parquet as default for <class 'pandas.core.frame.DataFrame'>, parquet already specified."}
{"asctime": "2022-12-25 22:57:07,317", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.PandasToParquetEncodingHandler object at 0x7fce624a8220> with format parquet as default for <class 'pandas.core.frame.DataFrame'>, parquet already specified."}
{"asctime": "2022-12-25 22:57:07,317", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.PandasToParquetEncodingHandler object at 0x7fce624a8220> with format parquet as default for <class 'pandas.core.frame.DataFrame'>, parquet already specified."}
{"asctime": "2022-12-25 22:57:07,317", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.ParquetToPandasDecodingHandler object at 0x7fce624549a0> with format parquet as default for <class 'pandas.core.frame.DataFrame'>, parquet already specified."}
{"asctime": "2022-12-25 22:57:07,317", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.ParquetToPandasDecodingHandler object at 0x7fce624549a0> with format parquet as default for <class 'pandas.core.frame.DataFrame'>, parquet already specified."}
{"asctime": "2022-12-25 22:57:07,317", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.ParquetToPandasDecodingHandler object at 0x7fce624549a0> with format parquet as default for <class 'pandas.core.frame.DataFrame'>, parquet already specified."}
{"asctime": "2022-12-25 22:57:07,317", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.ParquetToPandasDecodingHandler object at 0x7fce624549a0> with format parquet as default for <class 'pandas.core.frame.DataFrame'>, parquet already specified."}
{"asctime": "2022-12-25 22:57:07,317", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.ParquetToPandasDecodingHandler object at 0x7fce624549a0> with format parquet as default for <class 'pandas.core.frame.DataFrame'>, parquet already specified."}
{"asctime": "2022-12-25 22:57:07,317", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.ArrowToParquetEncodingHandler object at 0x7fce62454940> with format parquet as default for <class 'pyarrow.lib.Table'>, parquet already specified."}
{"asctime": "2022-12-25 22:57:07,318", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.ArrowToParquetEncodingHandler object at 0x7fce62454940> with format parquet as default for <class 'pyarrow.lib.Table'>, parquet already specified."}
{"asctime": "2022-12-25 22:57:07,318", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.ArrowToParquetEncodingHandler object at 0x7fce62454940> with format parquet as default for <class 'pyarrow.lib.Table'>, parquet already specified."}
{"asctime": "2022-12-25 22:57:07,318", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.ArrowToParquetEncodingHandler object at 0x7fce62454940> with format parquet as default for <class 'pyarrow.lib.Table'>, parquet already specified."}
{"asctime": "2022-12-25 22:57:07,318", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.ParquetToArrowDecodingHandler object at 0x7fce624a82b0> with format parquet as default for <class 'pyarrow.lib.Table'>, parquet already specified."}
{"asctime": "2022-12-25 22:57:07,318", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.ParquetToArrowDecodingHandler object at 0x7fce624a82b0> with format parquet as default for <class 'pyarrow.lib.Table'>, parquet already specified."}
{"asctime": "2022-12-25 22:57:07,318", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.ParquetToArrowDecodingHandler object at 0x7fce624a82b0> with format parquet as default for <class 'pyarrow.lib.Table'>, parquet already specified."}
{"asctime": "2022-12-25 22:57:07,318", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.ParquetToArrowDecodingHandler object at 0x7fce624a82b0> with format parquet as default for <class 'pyarrow.lib.Table'>, parquet already specified."}
{"asctime": "2022-12-25 22:57:07,318", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.ParquetToArrowDecodingHandler object at 0x7fce624a82b0> with format parquet as default for <class 'pyarrow.lib.Table'>, parquet already specified."}
```

## Type
 - [x] Bug Fix
 - [ ] Feature
 - [ ] Plugin

## Are all requirements met?

 - [x] Code completed
 - [ ] Smoke tested
 - [ ] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Complete description
^^^

## Tracking Issue
_NA_

## Follow-up issue
_NA_

### CODE REVIEW

**Review by eapolinario — COMMENTED** [review]
Shouldn't we also set the log level of https://github.com/flyteorg/flytekit/pull/1394/files#diff-65b1934afa4d0b61addbb0fcda54b6523c86ed9634812f0761bd2f36cb389a44R496 to `debug`?

**Comment by pingsutw** [comment]
sorry, which line? I already set [this line](https://github.com/flyteorg/flytekit/pull/1394/files#diff-65b1934afa4d0b61addbb0fcda54b6523c86ed9634812f0761bd2f36cb389a44R496) to debug.

**Review by wild-endeavor — COMMENTED** [review]
actually can you make it like this? https://github.com/flyteorg/flytekit/pull/1398/files#diff-65b1934afa4d0b61addbb0fcda54b6523c86ed9634812f0761bd2f36cb389a44R486

**Comment by pingsutw** [comment]
> sorry, which line? I already set [this line](https://github.com/flyteorg/flytekit/pull/1394/files#diff-65b1934afa4d0b61addbb0fcda54b6523c86ed9634812f0761bd2f36cb389a44R496) to debug.

sorry, line 496, I found that. some github issues, the link points to line 486...

**Review by wild-endeavor — APPROVED** [review]

**Pull request merged**
